### ISSUE TITLE
Error to create a new map and a new dashboard

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/austrocontrol-C125#211]
## Description

It is not possibile to create a new map and a new dashboard. The Save button does not work.

## How to reproduce

-  Open MapStore and login
- Click on New Maps  or New Dashbord
- Click on Burger Menu
- Click on Save as
- Enter a title

*Expected Result*

The Save button works and you can save the map/dashboard

*Current Result*

The Save button does not work for a new map and saving a dashboard a gray errror appears and the error on console is: 

>https://austrocontrol.geo-solutions.it/austrocontrol-ms2/rest/geostore/resources/

> Invariant Violation: [React Intl] An `id` must be provided to format a message.
    at e.exports (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:87:288231)
    at he (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:218:22117)
    at t.value (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:218:31175)
    at Ps (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:69087)
    at ks (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:68882)
    at La (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:104312)
    at tl (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:88795)
    at $a (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:88720)
    at Ga (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:85684)
    at https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45131
    at t.unstable_runWithPriority (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:264:3465)
    at No (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:44840)
    at zo (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45076)
    at Uo (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45011)
    at Na (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:82428)
    at Object.enqueueSetState (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:49708)

>  Invariant Violation: [React Intl] An `id` must be provided to format a message.
  at e.exports (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:87:288231)
    at he (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:218:22117)
    at t.value (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:218:31175)
    at Ps (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:69087)
    at ks (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:68882)
    at La (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:104312)
    at tl (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:88795)
    at $a (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:88720)
    at Ga (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:85684)
    at https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45131
    at t.unstable_runWithPriority (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:264:3465)
    at No (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:44840)
    at zo (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45076)
    at Uo (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:45011)
    at Na (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:82428)
    at Object.enqueueSetState (https://austrocontrol.geo-solutions.it/austrocontrol-ms2/dist/austrocontrol-ms2.js:202:49708)

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

**Comment by dsuren1** [comment]
@tdipisa 
With respect to issue with creation of dashboard. It seems like the resource category was missing in geostore **[name:DASHBOARD]**
I have added it and I can successfully save dashboard now . 
Meanwhile I will check the issue with saving the map

@ElenaGallo Kindly let me know if you can save dashboard
